### ISSUE TITLE
Prefix the CPT 

### ISSUE THREAD

**Issue by jmslbam** [level-level/clarkson-event-manager#2]
This one is still name `Event` instead of `Clarkson_Event`. https://github.com/level-level/clarkson-event-manager/blob/master/src/Event.php#L8

1. Should we rename this and move to 0.2.0?
2. Or rename and make "dummy" `Event` extend this new Clarkson Event? Keeps 0.1.0

I vote option 1. because fixing this in SOMO is just 1 simple step.

**Comment by NielsdeBlaauw** [comment]
I thought the `Clarkson` prefix in `Clarkson_Object` was because of the core project lacking a namespace. This project is already namespaced `\Clarkson\EventManager`. Is 
`Clarkson\EventManager\Clarkson_Event` not a bit excessive?

**Comment by jmslbam** [comment]
That was the answer I was looking for 👍  Closing this because the Events manager is already namespaced.
